### PR TITLE
Fix constructing from `b=-1`

### LINKED ISSUE #115: Constructing from `b=-1`
It's currently not possible to construct a `SemiclassicalJacobi` from `b=-1` except to `b=1`,

```julia
julia> P = SemiclassicalJacobi(2.0, -1/2, -1.0, -1/2);

julia> Q = SemiclassicalJacobi(2.0, -1/2, 0.0, -1/2, P);
ERROR: Polynomials must be orthonormal
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:35
 [2] cholesky_jacobimatrix(W::LazyBandedMatrices.Tridiagonal{…}, Q::SemiclassicalJacobi{…})
   @ ClassicalOrthogonalPolynomials C:\Users\danjv\.julia\packages\ClassicalOrthogonalPolynomials\3YYrU\src\choleskyQR.jl:53
 [3] semiclassical_jacobimatrix(Q::SemiclassicalJacobi{Float64}, a::Float64, b::Float64, c::Float64)
   @ SemiclassicalOrthogonalPolynomials C:\Users\danjv\.julia\packages\SemiclassicalOrthogonalPolynomials\GAsGB\src\SemiclassicalOrthogonalPolynomials.jl:194
 [4] SemiclassicalJacobi(t::Float64, a::Float64, b::Float64, c::Float64, P::SemiclassicalJacobi{Float64})
   @ SemiclassicalOrthogonalPolynomials C:\Users\danjv\.julia\packages\SemiclassicalOrthogonalPolynomials\GAsGB\src\SemiclassicalOrthogonalPolynomials.jl:127
 [5] top-level scope
   @ REPL[30]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

The call for `Q` should probably do something like

```julia
julia> Q = SemiclassicalJacobi(2.0, -1/2, 0.0, -1/2, SemiclassicalJacobi(P.t, P.a, one(P.b), P.c, P))
SemiclassicalJacobi with weight x^-0.5 * (1-x)^0.0 * (2.0-x)^-0.5 on 0..1
```

The `SemiclassicalJacobi(P.t, P.a, one(P.b), P.c, P)` call is efficient https://github.com/JuliaApproximation/SemiclassicalOrthogonalPolynomials.jl/blob/a1e4c3e65f164bc55f97f3574eb0da3ca62468ff/src/SemiclassicalOrthogonalPolynomials.jl#L174-L176

### PR DESCRIPTION
**Pull request by DanielVandH**
Fixes #115

### CODE REVIEW

File: src/SemiclassicalOrthogonalPolynomials.jl [hunk 1]
```diff
@@ -180,7 +180,10 @@ function semiclassical_jacobimatrix(Q::SemiclassicalJacobi, a, b, c)
         return Q.X
     elseif b == -one(eltype(Q.t))
         return semiclassical_jacobimatrix(Q.t, a, b, c)
-    end 
+    elseif Q.b == -one(eltype(Q.t))
+        newQ = SemiclassicalJacobi(Q.t, Q.a, one(Q.b), Q.c, Q)
```
Comment (TSGut) [inline src/SemiclassicalOrthogonalPolynomials.jl:184]: Why are we constructing with `one(Q.b)` instead of `zero(Q.b)`? Not saying it's wrong, just curious what the motivation is. What happens with this implementation if `b = 0`, does it hit some other special case?

Comment (DanielVandH) [reply src/SemiclassicalOrthogonalPolynomials.jl:184]: The case with `b = 1` is efficient (see Line 176). If we did `b = 0` it would have to be defined in terms of the `b = 1` case anyway since $P^{t, (a, -1, c)}$ is defined in terms of $P^{t, (a, 1, c)}$. I'll make a comment

File: test/test_neg1b.jl [hunk 2]
```diff
@@ -234,3 +234,15 @@ end
     @test_throws ArgumentError expand(HalfWeighted{:b}(P), g)
 end
 
+@testset "Issue #115" begin
```
[the remark this answers is not in the document]
Comment (DanielVandH) [reply test/test_neg1b.jl]: Good point, I agree. I've added titles to the two testsets in this repo with an `Issue #X` title
